const SHOW_WEATHER = "SHOW_WEATHER";
const CHANGE_REGION_OPTIONS = "CHANGE_REGION_OPTIONS";
const CONFIRM_REGION = "CONFIRM_REGION";
const CONFIRM_REGION_YES = "CONFIRM_REGION_YES";

export { 
    SHOW_WEATHER, CHANGE_REGION_OPTIONS, 
    CONFIRM_REGION, CONFIRM_REGION_YES   
};